---
title: "FAQ"
subtitle: "Syllabus - Fall 2025"
fontsize: 12pt
toc: false
format: 
  html: default
  pdf:
    mainfont: "Times New Roman"
    sansfont: "Times New Roman"
    include-in-header:
      - text: |
          \makeatletter
          \def\maketitle{
            \begin{center}
              {\normalfont\huge\@title}
            \end{center}
            \vskip 1em
            \begin{center}
              {\normalfont\large\@subtitle}
            \end{center}
            \vskip 1em
          }
          \makeatother
---

<br>

## Common Questions

<br>

### What if I already have in-depth DS/SWE/HWE/PM experience and feel that taking another course is overkill?

A: Those with significant technical experience may forgo the introductory track (coursework) and begin the recruitment process from the practical track (project-based "assessment"). Once you have completed the practical track and interview, you may join a project team immediately! Details on the recruitment process will be updated on the main page of this course site.

<br>

### Can I work on a DAML project while I work through the course?

A: We ask that all students complete the initial onboarding before working on internal or client projects. This onboarding does equip you with a beginner project, though.

<br>

### When can I begin the advanced project interview process?

A: Applications for the process have not yet been released. We will update you via newsletter and Slack when they do come out. 